apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ellamma-ecommerce
spec:
  type: {{ .Values.service.type }}
  selector:
    project: ecommerce-project
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #service Port
      targetPort: 27017 #container Port